name: 🆕 Feature Request
description: Suggest an idea for this project
title: "🆕 [FEATURE] <title>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe. A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you want to see
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or code snippets about the feature request here.
    validations:
      required: false
